---

- name: Increase maximum opened files limit
  sysctl:
    name: fs.inotify.max_user_watches
    value: 10032
    state: present
    reload: yes

- name: Increase maximum connection per machine
  sysctl:
    name: net.core.somaxconn
    value: 511
    state: present
    reload: yes
  when: redis_travis_ci is not defined

# This kernel setting affects how memory allocation is handled
# when a parent forks a child that starts to change the shared
# copy-on-write memory page. Without this setting, Redis might
# fail when dumping its dataset to disk.

- name: Enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  when: redis_travis_ci is not defined

- name: Add redis repository
  apt_repository:
    repo: 'ppa:chris-lea/redis-server'
    state: present

- name: Install redis package
  apt:
    pkg: redis-server
    state: latest
    update_cache: yes


